_BASE_: "./Base-AutoAssign.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SHIFT_GENERATOR:
    NUM_SHIFTS: 1
    OFFSET: 0.0
  AUTO_ASSIGN:
    # coco has 80 classes, but we only have 25 stroke classes
    NUM_CLASSES: 25 # default 80
DATALOADER:
  NUM_WORKERS: 8 # default 4, too slow
INPUT:
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 144
  MAX_SIZE_TRAIN: 144
  MIN_SIZE_TEST: 112
  MIN_SIZE_TRAIN: [ 112, 120 ]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 16 # default 16
  BASE_LR: 0.01  # Note that AutoAssign uses a different default learning rate
TEST:
  EVAL_PERIOD: 5000 # default 0, means no evaluation will be performed
VIS_PERIOD: 5000 # default 0, means no visualization will be performed
DATASETS:
  # <========= print dataset ===========>
  TRAIN: ("chinese_stroke_2021_train",)
  TEST: ("chinese_stroke_2021_val",)
  # <========= online dataset ===========>
  #  TRAIN: ("chinese_online_stroke_2021_train",)
  #  TEST: ("chinese_online_stroke_2021_val",)
TASKS: [ "bbox" ] # Note that autoassign only predict bbox and label
# the following fields are additionally added to init the env, set output log, and register dataset...
GPU_IDS: [ 0 ] # env related fields
OUTPUT_ID: autoassign_R_50_FPN_print_stroke_default_bs16 # output log are other files related fields default
#OUTPUT_ID: autoassign_R_50_FPN_print_stroke_improved # output log are other files related fields init
# dataset registration related fields
DATA_ROOT: /tmp/binary_chinese_stroke_2021
TRAIN_JSON_NAME: instances_train2021.json
VAL_JSON_NAME: instances_val2021.json
# <========= rgb print dataset ===========>
#DATASET_NAME: chinese_stroke_2021
#TRAIN_IMAGE_DIR: train2021
#VAL_IMAGE_DIR: val2021
# <========= binary print dataset ===========>
DATASET_NAME: chinese_stroke_2021
TRAIN_IMAGE_DIR: binarytrain2021
VAL_IMAGE_DIR: binaryval2021
# <========= rgb online dataset ===========>
#DATASET_NAME: chinese_online_stroke
#TRAIN_IMAGE_DIR: train2021
#VAL_IMAGE_DIR: val20201
# <========= binary online dataset ===========>
#DATASET_NAME: chinese_online_stroke
#TRAIN_IMAGE_DIR: binarytrain2021
#VAL_IMAGE_DIR: binaryval2021