MODEL:
  META_ARCHITECTURE: "AutoAssign"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: [ "res3", "res4", "res5" ]
  SHIFT_GENERATOR:
    NUM_SHIFTS: 1
    OFFSET: 0.0
  FPN:
    IN_FEATURES: [ "res3", "res4", "res5" ]
  AUTO_ASSIGN:
    IOU_LOSS_TYPE: "giou"
    PRIOR_PROB: 0.02
    REG_WEIGHT: 5.0
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that AutoAssign uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2