MODEL:
  META_ARCHITECTURE: "FCOS"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: [ "res3", "res4", "res5" ]
  SHIFT_GENERATOR:
    NUM_SHIFTS: 1
    OFFSET: 0.0
  FPN:
    IN_FEATURES: [ "res3", "res4", "res5" ]
  FCOS:
    CENTERNESS_ON_REG: false
    CENTER_SAMPLING_RADIUS: 0.0
    NMS_THRESH_TEST: 0.6
    NORM_REG_TARGETS: false
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2