_BASE_: "./Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: output/retinanet_R_50_FPN_print_stroke_default/20210716.073802/model_0219999.pth
  # WEIGHTS: output/retinanet_R_50_FPN_print_stroke_anchor_scale_init/20210716.075559/model_0234999.pth
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval [ "[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]" ] # default
    # SIZES: !!python/object/apply:eval [ "[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [ 16, 32, 64, 128, 256 ]]" ] # init
  RETINANET:
    # coco has 80 classes, but we only have 25 stroke classes
    NUM_CLASSES: 25 # default 80
DATALOADER:
  NUM_WORKERS: 8 # default 4, too slow
INPUT:
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 144
  MAX_SIZE_TRAIN: 144
  MIN_SIZE_TEST: 112
  MIN_SIZE_TRAIN: [ 112, 120 ]
DATASETS:
  # <========= handwritten dataset ===========>
  TRAIN: ("handwritten_stroke_2021_train",)
  TEST: ("handwritten_stroke_2021_val",)
  # <========= online dataset ===========>
  #  TRAIN: ("chinese_online_stroke_2021_train",)
  #  TEST: ("chinese_online_stroke_2021_val",)
TASKS: [ "bbox" ] # Note that retinanet only predict bbox and label
# the following fields are additionally added to init the env, set output log, and register dataset...
GPU_IDS: [ 0 ] # env related fields
OUTPUT_ID: retinanet_R_50_FPN_print_stroke_default_test # output log are other files related fields default
# OUTPUT_ID: retinanet_R_50_FPN_print_stroke_anchor_scale_init_test # output log are other files related fields init
# dataset registration related fields
DATA_ROOT: /tmp/binary_handwritten_stroke_2021
DATASET_NAME: handwritten_stroke_2021
TRAIN_JSON_NAME: instances_test2021.json
VAL_JSON_NAME: instances_test2021.json
# <========= rgb test dataset ===========>
# TRAIN_IMAGE_DIR: test2021
# VAL_IMAGE_DIR: test2021
# <========= binary test dataset ===========>
TRAIN_IMAGE_DIR: binarytest2021
VAL_IMAGE_DIR: binarytest2021
VIS_DATASET_RESULT: true # whether to visualize the dataset results
# <========= put the path of any images you want to visualize here ===========>
#IMAGE_PATHS: # default None, means not visualizing
#  - resources/inferenceImage/hard/mian-linmo.jpg
#  - resources/inferenceImage/hard/mian-shouxie.jpg
#  - resources/inferenceImage/hard/shu-linmo.jpg
#  - resources/inferenceImage/hard/shu-shouxie.jpg
#  - resources/inferenceImage/medium/jian-linmo.jpg
#  - resources/inferenceImage/medium/jian-shouxie.jpg
#  - resources/inferenceImage/medium/jian-yinshua.jpg
#  - resources/inferenceImage/medium/wen-linmo.jpg
#  - resources/inferenceImage/medium/wen-shouxie.jpg
#  - resources/inferenceImage/medium/wen-yinshua.jpg
#  - resources/inferenceImage/simple/san-linmo.jpg
#  - resources/inferenceImage/simple/san-shouxie.jpg
#  - resources/inferenceImage/simple/san-yinshua.jpg
#  - resources/inferenceImage/simple/yi-linmo.jpg
#  - resources/inferenceImage/simple/yi-shouxie.jpg
#  - resources/inferenceImage/simple/yi-yinshua.jpg
#  - resources/inferenceImage/whole.jpg
#  - resources/inferenceImage/dou.jpg
#  - resources/inferenceImage/dou1.jpg
#  - resources/inferenceImage/dou2.jpg
#  - resources/inferenceImage/dou_train_test.png