_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  # this weights only contains the pretrained backbone
  # we can also use the whole pretrained model (including both backbone and seg/det head)
  # from coco to improve the downstream task performance
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  MASKIOU_ON: True # for mask scoring rcnn
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
     SIZES: [ [ 16 ], [ 32 ], [ 64 ], [ 128 ], [ 256 ] ]  # One size for each in feature map init
     ASPECT_RATIOS: [ [ 0.5, 1.0, 2.0, 4.0 ] ]  # Three aspect ratios (same for all in feature maps) init
  ROI_HEADS:
    NAME: "MaskIOUROIHeads"
    # coco has 80 classes, but we only have 25 stroke classes
    NUM_CLASSES: 25 # default 80
DATALOADER:
  NUM_WORKERS: 8 # default 4, too slow
INPUT:
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 144
  MAX_SIZE_TRAIN: 144
  MIN_SIZE_TEST: 112
  MIN_SIZE_TRAIN: [ 112, 120 ]
SOLVER:
  STEPS: [ 210000, 250000 ] # default [210000, 250000]
  MAX_ITER: 270000 # default 270000
  WARMUP_ITERS: 1000 # default 1000
  CHECKPOINT_PERIOD: 5000 # default 5000
  IMS_PER_BATCH: 4 # default 16
  BASE_LR: 0.02 # default 0.02
TEST:
  EVAL_PERIOD: 5000 # default 0, means no evaluation will be performed
VIS_PERIOD: 5000 # default 0, means no visualization will be performed
DATASETS:
  # <========= print dataset ===========>
  TRAIN: ("chinese_stroke_2021_train",)
  TEST: ("chinese_stroke_2021_val",)
  # <========= online dataset ===========>
  #  TRAIN: ("chinese_online_stroke_2021_train",)
  #  TEST: ("chinese_online_stroke_2021_val",)
# the following fields are additionally added to init the env, set output log, and register dataset...
GPU_IDS: [ 0 ] # env related fields
# output log are other files related fields
OUTPUT_ID: mask_scoring_rcnn_R_50_FPN_3x_print_stroke_anchor_scale_init_relabeled
# dataset registration related fields
DATA_ROOT: /tmp/chinese_stroke_2021_relabeled
TRAIN_JSON_NAME: instances_train2021.json
VAL_JSON_NAME: instances_val2021.json
# <========= rgb print dataset ===========>
#DATASET_NAME: chinese_stroke_2021
#TRAIN_IMAGE_DIR: train2021
#VAL_IMAGE_DIR: val2021
# <========= binary print dataset ===========>
DATASET_NAME: chinese_stroke_2021
TRAIN_IMAGE_DIR: train2021
VAL_IMAGE_DIR: val2021
# <========= rgb online dataset ===========>
#DATASET_NAME: chinese_online_stroke
#TRAIN_IMAGE_DIR: train2021
#VAL_IMAGE_DIR: val2021
# <========= binary online dataset ===========>
#DATASET_NAME: chinese_online_stroke
#TRAIN_IMAGE_DIR: binarytrain2021
#VAL_IMAGE_DIR: binaryval2021
