MODEL:
  META_ARCHITECTURE: "Detr"
#  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 100
    FROZEN_WEIGHTS: ''
    NUM_CLASSES: 25
DATASETS:
  TRAIN: ("chinese_stroke_2021_train",)
  TEST: ("chinese_stroke_2021_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (55440,)
  MAX_ITER: 92400
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: False
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
GPU_IDS: [ 1 ] # env related fields
# output log are other files related fields
OUTPUT_ID: detr_segm_256_6_6_torchvision_stroke_default
# dataset registration related fields
DATA_ROOT: /tmp/binary_chinese_stroke_2021
TRAIN_JSON_NAME: instances_train2021.json
VAL_JSON_NAME: instances_val2021.json
# <========= binary print dataset ===========>
DATASET_NAME: chinese_stroke_2021
TRAIN_IMAGE_DIR: binarytrain2021
VAL_IMAGE_DIR: binaryval2021