_BASE_: "./detr_256_6_6_torchvision.yaml"
MODEL:
  META_ARCHITECTURE: "Detr"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 100
    NUM_CLASSES: 25
DATASETS:
  TRAIN: ("chinese_stroke_2021_train",)
  TEST: ("chinese_stroke_2021_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  # BASE_LR: 0.001
  # BASE_LR: 0.01
  STEPS: (369600,)
  MAX_ITER: 554400
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  # OPTIMIZER: "SGD"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MAX_SIZE_TEST: 224
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 112
  MIN_SIZE_TRAIN: [ 112, 120, 144, 224 ]
  CROP:
    ENABLED: True
    SIZE: (112, 112)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
TASKS: [ "bbox" ] # Note that dert only predict bbox and label
GPU_IDS: [ 0 ] # env related fields
# output log are other files related fields
# OUTPUT_ID: detr_256_6_6_torchvision_stroke_default
# OUTPUT_ID: vis_detr_256_6_6_torchvision_stroke_default
# OUTPUT_ID: detr_256_6_6_torchvision_stroke_default_fix_num_classes
# OUTPUT_ID: detr_256_6_6_torchvision_stroke_default_fix_num_classes_lr_1e-3
#OUTPUT_ID: detr_256_6_6_torchvision_stroke_default_fix_num_classes_lr_1e-2_sgd
OUTPUT_ID: detr_256_6_6_torchvision_stroke_default_crop
# dataset registration related fields
DATA_ROOT: /tmp/chinese_stroke_2021_relabeled
TRAIN_JSON_NAME: instances_train2021.json
VAL_JSON_NAME: instances_val2021.json
# <========= binary print dataset ===========>
DATASET_NAME: chinese_stroke_2021
TRAIN_IMAGE_DIR: train2021
VAL_IMAGE_DIR: val2021

