_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 25
  MASK_ON: True
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  ROI_HEADS:
    # coco has 80 classes, but we only have 25 stroke classes
    NUM_CLASSES: 25 # default 80
DATASETS:
  TRAIN: ("chinese_stroke_2021_train",)
  TEST: ("chinese_stroke_2021_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  MAX_SIZE_TEST: 224
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 112
  MIN_SIZE_TRAIN: [ 112, 120, 144, 224 ]
  CROP:
    ENABLED: False
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
VIS_PERIOD: 5000 # default 0, means no visualization will be performed
TASKS: [ "bbox", "segm" ]
GPU_IDS: [ 5 ] # env related fields
# output log are other files related fields
OUTPUT_ID: sparsercnn_seg_stroke_default_100pro_handwritten
OUTPUT_DIR: /mnt/cephfs/dataset/SIS_exp/liulizhao
# dataset registration related fields
DATA_ROOT: /mnt/cephfs/dataset/handwritten_chinese_stroke_2021
TRAIN_JSON_NAME: instances_train2021.json
VAL_JSON_NAME: instances_val2021.json
DATASET_NAME: chinese_stroke_2021
TRAIN_IMAGE_DIR: train2021
VAL_IMAGE_DIR: val2021