_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 25
DATASETS:
  TRAIN: ("chinese_stroke_2021_train",)
  TEST: ("chinese_stroke_2021_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  MAX_SIZE_TEST: 224
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 112
  MIN_SIZE_TRAIN: [ 112, 120, 144, 224 ]
  CROP:
    ENABLED: False
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
VIS_PERIOD: 5000 # default 0, means no visualization will be performed
TASKS: [ "bbox" ] # Note that dert only predict bbox and label
GPU_IDS: [ 0 ] # env related fields
# output log are other files related fields
OUTPUT_ID: sparsercnn_stroke_default_100pro_print_and_offline
# dataset registration related fields
DATA_ROOT: /tmp/print_and_offline_chinese_stroke_2021
TRAIN_JSON_NAME: instances_train2021.json
VAL_JSON_NAME: instances_val2021.json
DATASET_NAME: chinese_stroke_2021
TRAIN_IMAGE_DIR: train2021
VAL_IMAGE_DIR: val2021